services:
- type: web
  name: next-js
  runtime: node
  plan: starter
  buildCommand: cd ../.. && pnpm turbo build --filter=builder... && pnpm db:migrate
  startCommand: yarn start
  autoDeploy: false
  envVars:
  - key: NODE_ENV
    value: production